id: I4D55C4B9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T02:34:58+00:00'
last_modified: '2022-06-08T01:00:32.896125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2160
  title: ལྕགས་ཟམ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    0DFD:
      image_group_id: I3CN2162
      title: ''
      total_pages: 80
      order: 1
      base_file: 0DFD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
